name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - 'packages/is-even-by-cv/**'
      - 'packages/is-odd-by-cv/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - is-even-by-cv
          - is-odd-by-cv
        package-path:
          - packages/is-even-by-cv
          - packages/is-odd-by-cv
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Publish package
        run: |
          cd ${{ matrix.package-path }}
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          if echo "$CHANGED_FILES" | grep -q "${{ matrix.package }}"; then
            npm publish
          else
            echo "No changes in ${{ matrix.package }}, skipping publish."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
