name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - 'packages/is-even-by-cv/**'
      - 'packages/is-odd-by-cv/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - name: is-even-by-cv
            path: packages/is-even-by-cv
          - name: is-odd-by-cv
            path: packages/is-odd-by-cv
            
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Authenticate with npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Get current version
        run: |
          cd ${{ matrix.package.path }}
          CURRENT_VERSION=$(node -pe "require('./package.json').version")
        id: version
      - name: Publish package
        run: |
          cd ${{ matrix.package.path }}
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          if echo "$CHANGED_FILES" | grep -q "${{ matrix.package.name }}"; then
            npm version --no-git-tag-version ${CURRENT_VERSION}
            npm publish
          else
            echo "No changes in ${{ matrix.package.name }}, skipping publish."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
